title: iojqk inside
tagline: Shorty Line
description: Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum

author: 
  name: jackhu
  email: jack1012@gmail.com
  github: jack1012
theme: jekyll-theme-midnight
