title: iojqk inside
tagline: Site Tagline
description: Lorem Ipsum1 Lorem Ipsum2 Lorem Ipsum3 Lorem Ipsum4

author: 
  name: jackhu
  email: jack1012@gmail.com
  github: jack1012
theme: jekyll-theme-midnight

excerpt_separator:  '<!-- more -->'
